/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicMarker: typeof import('./src/components/markers/BasicMarker.vue')['default']
    BasicMarkerElement: typeof import('./src/components/markers/BasicMarkerElement.vue')['default']
    FeaturesList: typeof import('./src/components/FeaturesList/FeaturesList.vue')['default']
    GoogleMapLoader: typeof import('./src/components/GoogleMapLoader/GoogleMapLoader.vue')['default']
    GoogleMapMarker: typeof import('./src/components/GoogleMapMarker/GoogleMapMarker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
