export default [
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Khabarovsk Krai',
    federalSubject: '',
    city: 'Komsomol\'sk-na-Amure',
    complex: '',
    refinery: 'Komsomolsk refinery',
    fullNameEn: 'Komsomolsky Refinery',
    fullNameRu: 'ООО «РН-Комсомольский НПЗ»',
    name: 'Komsomolsk',
    lat: 50.54986,
    lng: 137.007867,
    mTPerYear: 7.23,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Irkutsk Oblast',
    federalSubject: 'Angarsky District',
    city: 'Angarsk',
    complex: '',
    refinery: 'Angarsk petrochemical company',
    fullNameEn: 'Angarsk Petrochemical Company',
    fullNameRu: 'АО «Ангарская нефтехимическая компания»',
    name: 'Angarsk',
    lat: 52.544911,
    lng: 103.888546,
    mTPerYear: 9.62,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Krasnoyarsk Krai',
    federalSubject: '',
    city: 'Achinsk',
    complex: '',
    refinery: 'Achinsk refinery',
    fullNameEn: 'Achinsk Refinery',
    fullNameRu: 'АО «Ачинский НПЗ ВНК»',
    name: 'Achinsk',
    lat: 56.253827,
    lng: 90.479474,
    mTPerYear: 7.15,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Tomsk Oblast',
    federalSubject: '',
    city: 'Strezhevoy',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Strezhevoy',
    lat: 60.732801,
    lng: 77.604047,
    mTPerYear: '',
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: 'Western Sibiria',
    administrativeDistrict: 'Khanty-Mansi Autonomous Okrug',
    federalSubject: '',
    city: 'Nizhnevartovsk',
    complex: '',
    refinery: 'Nizhne-Vartovsk Refinery Association',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Nizhnevartovsk',
    lat: 60.939751,
    lng: 76.569601,
    mTPerYear: '',
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Yamalo-Nenets Autonomous Okrug',
    federalSubject: '',
    city: 'Gubkinskiy',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Gubkinskiy',
    lat: 64.432625,
    lng: 76.500494,
    mTPerYear: '',
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Khanty–Mansi Autonomous Okrug',
    federalSubject: '',
    city: 'Nyagan',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Nyagan',
    lat: 62.14557,
    lng: 65.394514,
    mTPerYear: '',
  },
  {
    owner: 'Rosneft',
    company: 'Slavneft-YANOS PJSC',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Yaroslavl Oblast',
    federalSubject: '',
    city: 'Yaroslavl',
    complex: '',
    refinery: 'Novo-Yaroslavskiy refinery, Slavneft-Yaroslavnefteorgsintez (YANOS)',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Yaroslavl.Slavneft-YANOS',
    lat: 57.626569,
    lng: 39.893822,
    mTPerYear: 15.1,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: 'Southwestern Russia',
    administrativeDistrict: '‎Saratov Oblast',
    federalSubject: '',
    city: 'Saratov',
    complex: '',
    refinery: 'Saratov refinery',
    fullNameEn: 'Saratovsky Refinery',
    fullNameRu: 'ПАО «Саратовский НПЗ»',
    name: 'Saratovsk',
    lat: 51.531528,
    lng: 46.03582,
    mTPerYear: 6.71,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Samara Oblast',
    federalSubject: '',
    city: 'Novokuybyshevsk',
    complex: '',
    refinery: 'Novokuibyshev refinery',
    fullNameEn: 'Novokuibyshevsky Refinery',
    fullNameRu: 'АО «Новокуйбышевский НПЗ»',
    name: 'Novokuibyshevsk',
    lat: 53.099469,
    lng: 49.947767,
    mTPerYear: 8.05,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Samara Oblast',
    federalSubject: '',
    city: 'Syzran',
    complex: '',
    refinery: 'Syzran refinery',
    fullNameEn: 'Syzran Refinery',
    fullNameRu: 'АО «Сызранский НПЗ»',
    name: 'Syzran',
    lat: 53.155782,
    lng: 48.474485,
    mTPerYear: 6.91,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Ryazan Oblast',
    federalSubject: '',
    city: 'Ryazan',
    complex: '',
    refinery: 'Ryazan Refinery Company',
    fullNameEn: 'Ryazan Oil Refining Company',
    fullNameRu: 'АО «Рязанская нефтеперерабатывающая компания»',
    name: 'Ryazan.RNPK',
    lat: 54.629148,
    lng: 39.735243,
    mTPerYear: 15.78,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Krasnodar Krai',
    federalSubject: '',
    city: 'Tuapse',
    complex: '',
    refinery: 'Tuapse refinery',
    fullNameEn: 'Tuapse Refinery',
    fullNameRu: 'ООО «РН-Туапсинский НПЗ»',
    name: 'Tuapse',
    lat: 44.095232,
    lng: 39.073364,
    mTPerYear: 11.03,
  },
  {
    owner: 'Rosneft',
    company: 'Bashneft',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Ufimsky District',
    federalSubject: 'Bashkortostan',
    city: 'Ufa',
    complex: 'PJSC ANK BashNeft Refinery Complex',
    refinery: 'Bashneft-Novoil',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ufa.Novoil',
    lat: 54.880575201838,
    lng: 56.086537949929,
    mTPerYear: 5.99,
  },
  {
    owner: 'Rosneft',
    company: 'Bashneft',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Ufimsky District',
    federalSubject: 'Bashkortostan',
    city: 'Ufa',
    complex: 'PJSC ANK BashNeft Refinery Complex',
    refinery: 'Bashneft-Ufaneftekhim',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ufa.Ufaneftekhim',
    lat: 54.916990668091,
    lng: 56.082374927422,
    mTPerYear: 7.69,
  },
  {
    owner: 'Rosneft',
    company: 'Bashneft',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Ufimsky District',
    federalSubject: 'Bashkortostan',
    city: 'Ufa',
    complex: 'PJSC ANK BashNeft Refinery Complex',
    refinery: 'Bashneft-Ufa Refinery (UNPZ?)',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ufa.UNPZ',
    lat: 54.842378749633,
    lng: 56.103481474095,
    mTPerYear: 6.31,
  },
  {
    owner: 'Rosneft',
    company: '',
    country: 'Russia',
    region: 'Southwestern Russia',
    administrativeDistrict: 'Samara Oblast',
    federalSubject: '',
    city: 'Samara',
    complex: '',
    refinery: 'Kuibyshev refinery',
    fullNameEn: 'JSC Kuybyshevsky Oil Refinery',
    fullNameRu: 'АО «Куйбышевский НПЗ»',
    name: 'Kuibyshevsk',
    lat: 53.100175271859,
    lng: 50.068441369364,
    mTPerYear: 7,
  },
  {
    owner: 'Surgutneftegas',
    company: '',
    country: 'Russia',
    region: 'North West',
    administrativeDistrict: 'Leningrad Oblast',
    federalSubject: '',
    city: 'Kirishi',
    complex: '',
    refinery: 'LLC KINEF',
    fullNameEn: 'Kirishinefteorgsintez',
    fullNameRu: '',
    name: 'Kirishi.KINEF',
    lat: 59.492049484091,
    lng: 32.082569760757,
    mTPerYear: 17.7,
  },
  {
    owner: 'Gazprom Neft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Omsk',
    complex: '',
    refinery: 'Omsk Oil Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Omsk',
    lat: 55.072568820671,
    lng: 73.227367724126,
    mTPerYear: 22.23,
  },
  {
    owner: 'Gazprom Neft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Moscow',
    complex: '',
    refinery: 'Moscow Oil Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Moscow',
    lat: 55.841133778638,
    lng: 37.667277768783,
    mTPerYear: 8.86,
  },
  {
    owner: 'Gazprom',
    company: 'Salavatnefteorgsintez',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: 'Bashkortostan',
    city: 'Salavat',
    complex: '',
    refinery: 'Salavatnefteorgsintez Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Salavat',
    lat: 53.414151829737,
    lng: 55.887991362215,
    mTPerYear: 8.4,
  },
  {
    owner: 'Lukoil',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Perm',
    complex: '',
    refinery: 'Perm Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Perm',
    lat: 57.922122661214,
    lng: 56.142993323949,
    mTPerYear: 11.05,
  },
  {
    owner: 'Lukoil',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Ukhta',
    complex: '',
    refinery: 'Ukhta Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ukhta',
    lat: 63.574366882406,
    lng: 53.724382810557,
    mTPerYear: 3.51,
  },
  {
    owner: 'Lukoil',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Volgograd',
    complex: '',
    refinery: 'Volgograd Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Volgograd',
    lat: 48.49115120422,
    lng: 44.612476008472,
    mTPerYear: 15.7,
  },
  {
    owner: 'Lukoil',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Nizhny Novograd',
    complex: '',
    refinery: 'NORSI-oil',
    fullNameEn: '',
    fullNameRu: '',
    name: 'NORSI-oil',
    lat: 56.112021370928,
    lng: 44.133522895024,
    mTPerYear: 17,
  },
  {
    owner: 'SAFMAR',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Orsk',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Orsk.SAFMAR',
    lat: '',
    lng: '',
    mTPerYear: 5.57,
  },
  {
    owner: 'TAIF',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Nizhnekamsk',
    complex: '',
    refinery: 'TAIF-NK/Nizhnekamsk I',
    fullNameEn: '',
    fullNameRu: '',
    name: 'TAIF-NK',
    lat: '',
    lng: '',
    mTPerYear: 6.98,
  },
  {
    owner: 'Tatneft/TANEKO',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Nizhnekamsk',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Nizhnekamsk.TANEKO',
    lat: 55.576901143293,
    lng: 51.916022167035,
    mTPerYear: 7.38,
  },
  {
    owner: 'Новошахтинский завод нефтепродуктов',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Novoshakhtinsk',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Rostov.NZNP',
    lat: 47.833281059073,
    lng: 39.862093358132,
    mTPerYear: 8.44,
  },
  {
    owner: 'Russneft',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Krasnodar',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Krasnodar',
    lat: 45.003517588311,
    lng: 38.96822070005,
    mTPerYear: 2.55,
  },
  {
    owner: 'PJSC Orsknefteorgsintez',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Orsk',
    complex: '',
    refinery: 'Orsky Oil Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Orsk.Orsknefteorgsintez',
    lat: 51.254550651923,
    lng: 58.513349644057,
    mTPerYear: 5.76,
  },
  {
    owner: 'NefteChemService',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Kemerovo Oblast',
    federalSubject: '',
    city: 'Anzhero-Sudzhensk',
    complex: '',
    refinery: 'Ya-ya Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ya-ya',
    lat: 56.122058003405,
    lng: 86.135544869512,
    mTPerYear: 3.3,
  },
  {
    owner: 'Oil Company Alliance',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Khabarovsk',
    complex: '',
    refinery: 'Khabarovsk Oil Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Khabarovsk',
    lat: 48.49987096919,
    lng: 135.047681165,
    mTPerYear: 5,
  },
  {
    owner: 'Novatek',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Ust-Luga',
    complex: '',
    refinery: '',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ust-Luga',
    lat: 59.705114054987,
    lng: 28.438806815624,
    mTPerYear: 6.94,
  },
  {
    owner: 'Ilsky Oil Refinery',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: '',
    federalSubject: '',
    city: 'Il\'skii',
    complex: '',
    refinery: 'Ilsky Oil Refinery',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Ilsky',
    lat: 44.86084500651,
    lng: 38.607696700524,
    mTPerYear: 6.6,
  },
  {
    owner: 'LLC "Pervyy Zavod"',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Kaluga Oblast',
    federalSubject: '',
    city: 'Kaluga',
    complex: '',
    refinery: 'Pervyy Zavod',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Kaluga',
    lat: 54.711635730315,
    lng: 35.964959433345,
    mTPerYear: 1.2,
  },
  {
    owner: 'Slavyansk ECO Group',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Kaluga Oblast',
    federalSubject: '',
    city: 'Slavyansk-na-Kubani',
    complex: '',
    refinery: 'Pervyy Zavod',
    fullNameEn: '',
    fullNameRu: '',
    name: 'Slavyansk.ECO',
    lat: 45.229354811485,
    lng: 38.131555896718,
    mTPerYear: 4,
  },
  {
    owner: 'SAFMAR',
    company: '',
    country: 'Russia',
    region: '',
    administrativeDistrict: 'Kuban Oblast',
    federalSubject: '',
    city: 'Afipsky',
    complex: '',
    refinery: 'Afipsky',
    fullNameEn: '',
    fullNameRu: 'Ooo "Афипский НПЗ"',
    name: 'Afipsky',
    lat: 44.8847744064469,
    lng: 38.82940325158764,
    mTPerYear: 6,
  },
]
